#include 'protheus.ch'
#include 'fwmvcdef.ch'
#include 'tlpp-core.th'

// Obrigatoriedade de Namespace em TLPP
namespace MvcLogin

/*/{Protheus.doc} CadLoginEvents
Classe Observer para tratamento de eventos do modelo CadLogin
@type class
@author eduardo.brust
@since 19/04/2026
/*/
class CadLoginEvents From FWModelEvent

	//atributos
	PRIVATE data  oBrowseTable as object
	PRIVATE data  cTitulo as character
	PRIVATE data  cUrlProtheus as character
	PRIVATE data  cUsuario as character
	PRIVATE data  cSenha as character
	PRIVATE data  dDataAtual as date

	//métodos
	protected Method New() CONSTRUCTOR //metodo construtor da classe
	protected Method finish() //limpar  os objetos e arrays da memória antes de eliminar a instancia da classe
	protected Method BrowseDef()  //definicao do browser da tela

	public Method ModelPosVld(oModel as object, cModelId as character) as logical
	public Method AfterTTS(oModel as object, cModelId as character)

	Static Method CadastraLoginHml()  //método estático para cadastro de login na base de homologação, será chamado externamente via job / scheduler
	protected Method RetornaCadLogin() as Logical  //método para retornar os dados da tabela de cadastro de login
	Private Method ConectaApiLogin(jLogin as json, cToken as character)  as logical //método para conectar na API do protheus de cadastro de usuarios
	Private Method AtualizaCadLogin(cLogin as character,cDataIn as character) //método para atualizar os dados da tabela de cadastro de login
	Private Method ProtheusToken() as character //método para obter o token de acesso as APIs do protheus via API
	Public Method InfoServer() as Logical //método para obter informações do server
endclass

/*/{Protheus.doc} CadLoginEvents::New
É o **método construtor** da classe. Ele é responsável por inicializar os atributos essenciais
@type method
@author eduardo.brust
@since 19/04/2026
@return object, retorna a instancia do objeto
/*/
method New() class CadLoginEvents
	// inicialização dos atributos
	::oBrowseTable := nil
	::cTitulo     := "MVC - TLPP - Cadastro de Login para base de Homologação "
	::cUrlProtheus := ""
	::cUsuario := ""
	::cSenha := ""
	::dDataAtual := Date()
return self


/*/{Protheus.doc} CadLoginEvents::finish
Método destinado à **limpeza de memória**. Ele desativa e destrói o objeto de Browse
@type method
@author eduardo.brust
@since 19/04/2026
/*/
Method finish() CLASS CadLoginEvents

	//limpo o componente de tela
	If ::oBrowseTable <> Nil
		::oBrowseTable:DeActivate()
		::oBrowseTable:Destroy()
		::oBrowseTable := Nil
	EndIf
	::cTitulo := ""
	::cUrlProtheus := ""
	::cUsuario := ""
	::cSenha := ""
	::dDataAtual := Date()
Return

/*/{Protheus.doc} CadLoginEvents::ModelPosVld
Método de pós-validação total do modelo (TudoOk).
@type method
@author eduardo.brust
@since 19/04/2026
@return logical, retorna .t. ou .f. dependendo da validação
/*/
method ModelPosVld(oModel as object, cModelId as character) as logical class CadLoginEvents
	local lRet := .T. as logical
return lRet

method AfterTTS(oModel as object, cModelId as character) class CadLoginEvents
	FWAlertSuccess("Processo concluído para o modelo: " + cModelId, "CadLogin")
return

/*/{Protheus.doc} CadLoginEvents::BrowseDef
definicao do browser da tela
@type method
@author eduardo.brust
@since 19/04/2026
/*/
Method BrowseDef() CLASS CadLoginEvents

	//Criando o browse da temporária
	::oBrowseTable := FWMBrowse():New()
	::oBrowseTable:SetAlias("ZZG")

	::oBrowseTable:AddLegend("DTOS(ZZG->ZZG_DATAIN) >= '" + dtos(::dDataAtual) + "' .AND. ZZG->ZZG_STATUS <> 'I'","GREEN"	,"Login Cadastrado")
	::oBrowseTable:AddLegend("DTOS(ZZG->ZZG_DATAIN) < '" + dtos(::dDataAtual) + "' .AND. ZZG->ZZG_STATUS <> 'I'","ORANGE"	,"Login Pendente Cadastro")
	::oBrowseTable:AddLegend("ZZG->ZZG_STATUS == 'I'","RED"	    ,"Login Inativo")

	::oBrowseTable:SetUseCaseFilter(.T.)
	::oBrowseTable:DisableDetails()
	::oBrowseTable:SetDescription(::cTitulo)
	::oBrowseTable:SetMenuDef("MvcLogin.CadLogin")
	::oBrowseTable:Activate()

return


Method CadastraLoginHml() CLASS CadLoginEvents
	Local lRet := .F. as logical
	Local oCadLogin as object

	oCadLogin := MvcLogin.CadLoginEvents():New()  //instancio o objeto da classe

	lRet := oCadLogin:InfoServer() //chamo o método para verificar se o ambiente é de teste/homologação

	If ISBLIND() .OR. GetRemoteType() == -1 .OR. !TCIsConnected()
		RpcClearEnv()
		RpcSetEnv( '99','01',,,,,) // trocar pelos parâmetros corretos de ambiente, filial, etc conforme sua necessidade
	endif

	if lRet // se for ambiente de teste ou homologação
		//chamo metódo que retorna os dados da tabela de cadastro de login via API do protheus, para preencher o browse da tela
		lRet := oCadLogin:RetornaCadLogin()
	else
		varinfo("A Tag [AMBIENTE_AGUAS] nao foi localizada ou esta incorreta no arquivo de configuracao (.ini). O acesso via API nao foi autorizado; verifique o arquivo no servidor.", "CadLogin")
	endif

	If ISBLIND() .OR. GetRemoteType() == -1 .OR. !TCIsConnected()
		RpcClearEnv()
		VARINFO("Rotina executada em ambiente sem conexão, resultados não serão apresentados na tela.", "CadLogin")
	else
		if lRet
			FWAlertSuccess("Login cadastrado com sucesso", "Api Login")
		else
			FWAlertError("Falha ao cadastrar o login", "Api Login")
		endif
	endif

	freeObj(oCadLogin)
	oCadLogin := nil
return

Method RetornaCadLogin() as Logical CLASS CadLoginEvents
	local cQuery as character //query para consulta
	Local oStatement      as object
	local nParamOrder := 1 as numeric //ordem dos parametros
	Local cAlias as character //alias para o browse
	local cLifeTime := "600" as character //tempo de vida da consulta
	local cTimeOut := "120" as character //tempo de espera da consulta
	Local jLogin as json //monto os dados do login em formato json para enviar via API
	Local cToken := "" as character //variável para armazenar o token de acesso as APIs do protheus
	Local lRet := .F. as logical

	cQuery := ""

	cQuery += " SELECT * "  + CRLF
	cQuery += " FROM    ? ZZG " + CRLF
	cQuery += " WHERE ZZG.d_e_l_e_t_ = ? " + CRLF
	cQuery += " AND ZZG_DATAIN < ? " + CRLF
	cQuery += " AND ZZG_STATUS <> ? " + CRLF
	cQuery += " ORDER BY 1,2 " + CRLF

	oStatement := FWExecStatement():New(cQuery)

	oStatement:SetUnsafe(nParamOrder++, RetSqlName('ZZG')) // nome da tabela
	oStatement:SetString(nParamOrder++, space(1)) // para selecionar registros não deletados
	oStatement:SetString(nParamOrder++, dtos(::dDataAtual)) // para selecionar registros com data de cadastro menor que a data atual, ou seja, pendentes
	oStatement:SetString(nParamOrder++, "I") 	// para selecionar registros com status <> I inativos

	//Recupera a consulta já com os parâmetros injetados
	cFinalQuery := oStatement:GetFixQuery()

	cAlias := oStatement:OpenAlias(GetNextAlias(),cLifeTime,cTimeOut)

	//percorro o alias data tabela para cadastro do login via API, caso haja algum registro sem data de cadastro (pendente)
	while !(cAlias)->(Eof())

		if empty(cToken)
			cToken := ::ProtheusToken() //chamo o método para obter o token de acesso as APIs do protheus somente 1x
			if empty(cToken)
				VARINFO("Nao foi possivel obter o token de acesso do Protheus para a API de cadastro . Verifique as configuracoes e a conectividade com o servidor.", "CadLogin")
				return .F.
			endif
		endif

		jLogin := JsonObject():New()
		jLogin["LOGIN"] := LOWER(ALLTRIM((cAlias)->ZZG_LOGIN))
		jLogin["NOME"] := LOWER(ALLTRIM((cAlias)->ZZG_NOME))
		jLogin["GRUPO"] := LOWER(ALLTRIM((cAlias)->ZZG_GRUPO))
		jLogin["EMAIL"] := LOWER(ALLTRIM((cAlias)->ZZG_EMAIL))
		jLogin["CARGO"] := LOWER(ALLTRIM((cAlias)->ZZG_CARGO))
		JLogin["DEPART"] := LOWER(ALLTRIM((cAlias)->ZZG_DEPART))

		IF ::ConectaApiLogin( jLogin, cToken) //chamo o método de conexão com a API para cadastro do login, passando os dados do login em formato json

			//caso a conexão com a API seja bem sucedida, atualizo a data de cadastro do login na tabela
			::AtualizaCadLogin((cAlias)->ZZG_LOGIN, DTOS(Date()))
			VARINFO("Login " + (cAlias)->ZZG_LOGIN + " cadastrado com sucesso via API", "CadLogin")
			lRet := .T.
		ELSE
			VARINFO("Falha ao cadastrar o login " + (cAlias)->ZZG_LOGIN + " via API", "CadLogin")
		ENDIF
		(cAlias)->(dbSkip())
	enddo

return lRet

Method ConectaApiLogin(jLogin as json, cToken as character)  as logical CLASS CadLoginEvents
	Local aHeader   := {}
	Local cResource := "/api/framework/v1/users/" // Endpoint de gravação conforme sua imagem
	Local cResult   := ""
	Local oRest     := Nil
	Local lRet      := .F.
	Local jBody := JsonObject():New() as json
	Local cBody := ""


	// --- MONTAGEM DO BODY (Conforme o seu JSON) ---
	jBody["userName"]      := jLogin["LOGIN"]
	jBody["displayName"]   := jLogin["NOME"]

	// Objeto aninhado 'name'
	jBody["name"]          := JsonObject():New()
	jBody["name"]["formatted"] := "Usuario Modelo Fonte"
	jBody["name"]["givenName"] := "Usuario"
	jBody["name"]["familyName"]:= "Modelo"

	// Array de Emails
	jBody["emails"]        := {}
	aAdd(jBody["emails"], JsonObject():New())
	jBody["emails"][1]["value"]   := jLogin["EMAIL"]
	jBody["emails"][1]["type"]    := "work"
	jBody["emails"][1]["primary"] := .T.

	jBody["password"]      := "Gab@12345" // defino uma senha provisória que será trocada no primeiro acesso
	jBody["active"]        := .T.
	jBody["administrator"] := .T.

	// Array de Groups
	jBody["groups"]        := {}
	aAdd(jBody["groups"], JsonObject():New())
	jBody["groups"][1]["value"]   := jLogin["GRUPO"]
	jBody["groups"][1]["display"] := "Administradores"

	// Array de Roles
	jBody["roles"]         := {}
	aAdd(jBody["roles"], JsonObject():New())
	jBody["roles"][1]["value"]    := "000000"
	jBody["roles"][1]["company"]  := "0"
	jBody["roles"][1]["action"]   := "UpSert"

	jBody["title"]         := 	jLogin["CARGO"]
	jBody["department"]    := jLogin["DEPART"]

	// Converte o objeto JSON para string
	cBody := EncodeUTF8(jBody:ToJson())

	// Definição do Header com o Token recebido
	aAdd(aHeader, "Content-Type: application/json")
	aAdd(aHeader, "Accept: application/json")
	//aAdd(aHeader, "tenantId: 99,01")

	// Injeção do Token no padrão Bearer
	aAdd(aHeader, "Authorization: Bearer " + AllTrim(cToken))
	aAdd(aHeader, "Content-Length: " + cValToChar(Len(cBody)))

	oRest := FWRest():New(::cUrlProtheus)  //conecto ao EndPoint do serviço
	oRest:SetPath(cResource)
	oRest:SetPostParams(cBody)

	// 4. Execução do POST
	If oRest:Post(aHeader)
		cResult := oRest:GetResult()
		varinfo("Sucesso ao gravar usuario: " + cResult, "CadLogin")
		lRet := .T.
	Else
		IF VALTYPE(oRest) <> "O"
			varinfo("Falha na conexao com a API: Objeto de conexao invalido", "CadLogin")
		else
			cResult := oRest:GetLastError()
			varinfo("Erro na gravacao do usuario: " + cResult, "CadLogin")
		endif
	EndIf

	FreeObj(oRest)
Return lRet

method ProtheusToken()  class CadLoginEvents
	Local cResource	:= "/api/oauth2/v1/token?grant_type=password" as Character
	Local aHeader	:= {} as Array
	Local oRet		:= Nil as object
	Local cResult	:= "" as Character

	oRet := FWRest():New(::cUrlProtheus)  //conecto ao EndPoint do serviço

	oRet:SetPath(cResource)		 	//defino a url final de conexao

	// Inclusão de parametros no Header
	aAdd(aHeader,"Content-Type: application/json")
	aAdd(aHeader,"Accept: application/json" )
	aAdd(aHeader,"username: " + ::cUsuario )
	aAdd(aHeader,"password: " + ::cSenha )

	//TRATAMENTO DE ERRO
	if VALTYPE(oRet) <> "O"
		return cResult
	endif

	oRet:SetPostParams()

	If (oRet:Post(aHeader))

		//recupero o json retornado
		cResult	:= oRet:GetResult()

		//trato o json
		oJson	:= JsonObject():new()
		oJson:fromJson(cResult)

		//recupero o token
		cResult	:= 	oJson:GetJsonText("access_token")
	else
		cResult	:= ""
		varinfo("Falha ao obter o token de acesso via API: " + oRet:GetLastError(), "CadLogin")
	endif
return cResult

Method AtualizaCadLogin(cLogin as character, cDataIn as character) CLASS CadLoginEvents
	Local cUpdate as character
	Local nRet as numeric

	Default cDataIn := ""
	Default cLogin := ""

	IF !EMPTY(cLogin) .AND. !EMPTY(cDataIn)
		cUpdate := ""
		cUpdate += " UPDATE " +  RetSqlName("ZZG") + " SET ZZG_DATAIN = '" + cDataIn + "' " + CRLF
		cUpdate += " WHERE D_E_L_E_T_ = ' ' " + CRLF
		cUpdate += " AND ZZG_LOGIN = '" + cLogin + "' " + CRLF

		nRet := TCSQLExec(cUpdate) // Atualiza a temporária localment
		IF  EMPTY(TCSQLError())
			VARINFO("Data de cadastro atualizada para o login " + cLogin, "CadLogin")
		ELSE
			VARINFO("Falha ao atualizar a data de cadastro para o login " + cLogin, "CadLogin")
			VARINFO("TCSQLError() " + TCSQLError(), "CadLogin")
		endif
	ENDIF

return

Method InfoServer() as Logical CLASS CadLoginEvents
	Local cIniName		:= ""
	Local cAmbiente		:= ""
	Local cAmbValidos 	:= "|TESTE|HOMOLOGACAO|" as character
	Local lUrlOk      	:= .F. as logical
	Local lRet			:= .F. as logical  // se retornar .T. ambiente é teste ou homologacao

	//VERIFICAR SE O AMBIENTE EM EXECUÇÃO É BASE TESTE OU PRODUÇÃO BUSCANDO UMA CHAVE NO INI QUE A ROTINA IRA RODAR
	cIniName	:= ALLTRIM(GetSrvIniName())

	//TRATAMENTO DE ERRO
	IF VALTYPE(cIniName) == "C"
		cAmbiente	:= ALLTRIM(GetPvProfString("AMBIENTE_AGUAS", "TIPO", "", cIniName))
		::cUrlProtheus := ALLTRIM(GetPvProfString("AMBIENTE_AGUAS", "URL_PROTHEUS", "", cIniName))
		::cUsuario := ALLTRIM(GetPvProfString("AMBIENTE_AGUAS", "USUARIO", "", cIniName))
		::cSenha := ALLTRIM(GetPvProfString("AMBIENTE_AGUAS", "SENHA", "", cIniName))
	ENDIF

	//TRATAMENTO DE ERRO
	IF VALTYPE(cAmbiente) <> "C"
		cAmbiente := ""
	ENDIF

	//TRATAMENTO DE ERRO
	IF VALTYPE(::cUrlProtheus) <> "C"
		::cUrlProtheus := ""
	ENDIF

	//TRATAMENTO DE ERRO
	IF VALTYPE(::cUsuario) <> "C"
		::cUsuario := ""
	ENDIF

	//TRATAMENTO DE ERRO
	IF VALTYPE(::cSenha) <> "C"
		::cSenha := ""
	ENDIF

	// Testo se a URL contém algum dos prefixos de desenvolvimento/homologação
	lUrlOk := ( UPPER("d1") $ UPPER(::cUrlProtheus) .OR. ;
		UPPER("hml") $ UPPER(::cUrlProtheus) .OR. ;
		UPPER("localhost") $ UPPER(::cUrlProtheus) .OR. ;
		UPPER("dev") $ UPPER(::cUrlProtheus) )

	varinfo("Ambiente identificado: " + cAmbiente, "CadLogin")
	varinfo("URL do Protheus para conexao: " + ::cUrlProtheus, "CadLogin")
	varinfo("Usuario para conexao API: " + ::cUsuario, "CadLogin")
	varinfo("Senha para conexao API: " + (IIF(!EMPTY(::cSenha), "********", "Nao informada")), "CadLogin")
	varinfo("Validacao de url: " + (IIF(lUrlOk, "OK", "Falhou - URL nao parece ser de teste/homologacao")), "CadLogin")
	varinfo("Validacao de Ambiente: " + (IIF(UPPER(cAmbiente) $ UPPER(cAmbValidos), "OK", "Falhou - Ambiente nao e Teste ou Homologacao")), "CadLogin")

	// Validação final
	IF UPPER(cAmbiente) $ UPPER(cAmbValidos) .AND. lUrlOk .AND. ;
			!EMPTY(::cUsuario) .AND. !EMPTY(::cSenha)
		lRet := .T.
	ENDIF

Return lRet

/*/{Protheus.doc} CadLogin
Função principal (Entry Point) renomeada para CadLogin
@type function
@author eduardo.brust
@since 19/04/2026
/*/
User Function CadLogin()
	local aArea as array

	Private oCadLogin as object

	aArea := getArea()

	oCadLogin := MvcLogin.CadLoginEvents():New()  //instancio o objeto da classe

	//Criando o browse da temporária
	oCadLogin:BrowseDef()

	//chamo metódo para limpeza dos objetos da clase
	oCadLogin:finish()

	//elimino a instancia da classe em memória
	FreeObj(oCadLogin)
	oCadLogin := nil

	//restauro a área do protheus em memória
	FWRestArea(aArea)
Return NIL

/*/{Protheus.doc} MenuDef
Retorna um array com as **opções de menu** disponíveis na rotina. Define quais operações o usuário pode realizar, 
como Pesquisar, Visualizar, Incluir, Alterar, Excluir, Imprimir e Copiar.
@type function
@author eduardo.brust
@since 19/04/2026
@return array, Array contendo as opções da rotina, algumas opções
não são apresentadas diretamente como botões, é necessário ir nas
outras ações
/*/
User Function MenuDef() as array
	local aRotina := {} as array

	// As referências de Action devem conter o Namespace completo
	Add Option aRotina Title "Visualizar" Action "ViewDef.MvcLogin.CadLogin" Operation OP_VISUALIZAR Access 0
	Add Option aRotina Title "Incluir"    Action "ViewDef.MvcLogin.CadLogin" Operation OP_INCLUIR    Access 0
	Add Option aRotina Title "Alterar"    Action "ViewDef.MvcLogin.CadLogin" Operation OP_ALTERAR    Access 0
	Add Option aRotina Title "Excluir"    Action "ViewDef.MvcLogin.CadLogin" Operation OP_EXCLUIR    Access 0
	Add Option aRotina Title "API Login"  Action "MvcLogin.CadLoginEvents():CadastraLoginHml()" Operation OP_INCLUIR    Access 0
Return aRotina

/*/{Protheus.doc} ModelDef
Definição do modelo de dados (Aberto/Público em TLPP)
@type function
@author eduardo.brust
@since 19/04/2026
@return object, retorna o objeto do model
/*/
User Function ModelDef() as object
	local oModel    as object
	local oStruZZG  := FWFormStruct(1, "ZZG")

	// O ID do Modelo (CadLoginM) não pode ser igual ao nome da User Function (CadLogin)
	oModel := MPFormModel():New("CadLoginM")

	oModel:AddFields('CAB', , oStruZZG)

	// Adiciona a descrição do Componente do Modelo de Dados
	oModel:GetModel( 'CAB' ):SetDescription( 'Cadastro de Login para base de homologação' )

	//define a chave
	oModel:SetPrimaryKey({"ZZG_FILIAL", "ZZG_LOGIN"})

	// Instalação do Observer
	oModel:InstallEvent("BordEvents", , MvcLogin.CadLoginEvents():New())

Return oModel

/*/{Protheus.doc} ViewDef
Define a **Interface Visual (View)** da rotina. Ela determina como os campos serão exibidos
@type function
@author eduardo.brust
@since 19/04/2026
@return object, Objeto do tipo FwFormView
/*/
User Function ViewDef() as object
	local oView     as object
	Local oStruZZG 	as object

	// O carregamento do modelo exige o nome completo (Namespace + Função)
	oModel    := FWLoadModel("MvcLogin.CadLogin")
	oStruZZG  := FWFormStruct(2, "ZZG")


	// Cria o objeto de View
	oView := FWFormView():New()

	// Define qual o Modelo de dados será utilizado na View
	oView:SetModel( oModel )
	// Adiciona no nosso View um controle do tipo formulário
	// (antiga Enchoice)
	oView:AddField( 'VIEW_CAB', oStruZZG, 'CAB' )

	// Criar um "box" horizontal para receber algum elemento da view
	oView:CreateHorizontalBox( 'SUPERIOR' 	, 100)

	// Relaciona o identificador (ID) da View com o "box" para exibição
	oView:SetOwnerView( 'VIEW_CAB'	, 	'SUPERIOR' 	)


	// Retorna o objeto de View criado
	oView:EnableTitleView('VIEW_CAB','Cadastro de Login - Base de Homologação')

Return oView

User Function JobCadLoginHml()

	MvcLogin.CadLoginEvents():CadastraLoginHml()

return
